apiVersion: v1
kind: Service
metadata:
    name: lexorodemopipelinesjavascriptdocker
spec:
    type: LoadBalancer
    ports:
    - port: 8087 
    selector:
        app: lexorodemopipelinesjavascriptdocker
